### ISSUE TITLE
question: web3.storage API key & WebRecorder

### ISSUE THREAD

**Issue by akhileshthite** [JusticeEngineering/pin-tweet-to-ipfs#134]
The latest version of this extension is not taking web3.storage API key from the user, but I saw that it's taking the API key from user in the extension demo video. Do you think that storing user API key is a bad idea? I also have a chrome extension called [DScan](https://chrome.google.com/webstore/detail/dscan-decentralized-qr-co/idpfgkgogjjgklefnkjdpghkifbjenap) and I'm planning to use [w3up](https://blog.web3.storage/posts/announcing-w3up-beta-v2) to solve this problem.

**Comment by akhileshthite** [comment]
You're using WebRecorder to convert those tweet links into embed files, is there any way to publish links to IPFS directly without the need of file (IPFS link will open that URL directly)?

**Comment by meandavejustice** [comment]
@akhileshthite we plan to add back an option for a user to input their own api key for web3.storage. We decided having a shared key would be easier for less-technical users.

> Do you think that storing user API key is a bad idea?

No I think that is fine. I would store in local storage.

>  is there any way to publish links to IPFS directly without the need of file

I don't think I understand the question here. Can you elaborate?

**Comment by akhileshthite** [comment]
> @akhileshthite we plan to add back an option for a user to input their own api key for web3.storage. We decided having a shared key would be easier for less-technical users.
> 
> > Do you think that storing user API key is a bad idea?
> 
> No I think that is fine. I would store in local storage.
> 
> > is there any way to publish links to IPFS directly without the need of file
> 
> I don't think I understand the question here. Can you elaborate?

Okay, got it.

So coming to my question -> I mean, can we redirect urls to IPFS?
Like for example, a URL shortener..

**Comment by meandavejustice** [comment]
> So coming to my question -> I mean, can we redirect urls to IPFS?

You mean having a link in the panel for 
`ipfs://bafybeibqo44vm4ib64qwp6wsiigktcoyubvivpup22cvozfo7ffxbncdoa/`
instead of `https://bafybeibqo44vm4ib64qwp6wsiigktcoyubvivpup22cvozfo7ffxbncdoa.ipfs.w3s.link/`?
